-- Add READY_TO_COLLECT status to order_intents
ALTER TABLE order_intents
    MODIFY COLUMN status ENUM('PAYMENT_PENDING', 'QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED', 'PAYMENT_FAILED', 'READY_TO_COLLECT') NOT NULL DEFAULT 'PAYMENT_PENDING';
